### ISSUE TITLE
Allowing style extensions

### ISSUE THREAD

**Issue by johanneslumpe** [robinweser/kilvin#2]
Right now we cannot extend the component base styles and have to resort to inline styles for customization. How about we add an `extendStyles` prop, which takes an object and passes that one to `extend`?

**Comment by robinweser** [comment]
This will be done with the next release :P

**Comment by robinweser** [comment]
Well or probably not. With react-fela 4.2 we can simple do the following:

```javascript
const extended = (props) => ({
  extend: [
    condition: props.isExtended,
    style: { ... }
  ]
})

const ExtendedBox = createComponent(extended, Box)

<ExtendedBox flex='1 0 auto' justifyContent='center' isExtended />
```

**Comment by johanneslumpe** [comment]
@rofrischmann is this also what you'd recommend now to make these components work with media queries? Just wrap and use `mapValueToMediaQuery`?

**Comment by robinweser** [comment]
Yeah, that's actually how I myself do it. See http://fela.js.org/docs/recipes/ResponsiveComponents.html

**Comment by johanneslumpe** [comment]
@rofrischmann awesome!
