### ISSUE TITLE
The invalid value `true` has been used as `flex`.

### ISSUE THREAD

**Issue by johanneslumpe** [robinweser/kilvin#3]
When using `<Box flex>`, chrome outputs this warning:

> The invalid value `true` has been used as `flex`

I assume this warning comes from the fela validator, but that means that props are incorrectly processed or passed though I assume.

A workaround is to use `<Box flex={1} />` but the whole reason the `flex` prop exists is because it's supposed to be a shortcut, right?

**Comment by robinweser** [comment]
Is this still an issue? I've totally forgotten this one :/
